# Generated by https://smithery.ai
# Use Node.js 18-alpine as the base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install ALL dependencies (including dev dependencies)
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Start new stage for production
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy only the necessary files from builder
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install ONLY production dependencies
# --omit=dev : Skip dev dependencies
# --ignore-scripts : Don't run scripts like prepare/postinstall
RUN npm ci --omit=dev --ignore-scripts

# Set environment variables
ENV DEEPSEEK_API_KEY=your-api-key-here
ENV NODE_ENV=production

# Command to run the server
CMD ["node", "build/index.js"]