# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 18-alpine as the base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies including devDependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Prepare the runtime image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy built application from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies without running scripts
RUN npm ci --omit=dev --ignore-scripts

# Set environment variables (ensure to replace with your actual API key)
ENV DEEPSEEK_API_KEY=your-api-key-here

# Command to run the server
CMD ["node", "build/index.js"]