# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 18-alpine as the base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Prepare the runtime image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy built application from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --only=production

# Set environment variables (ensure to replace with your actual API key)
ENV DEEPSEEK_API_KEY=your-api-key-here

# Expose necessary ports (if applicable)
# EXPOSE 8080  # Example: adjust according to your needs

# Command to run the server
CMD ["node", "build/index.js"]
